### PR TITLE
cmake: hardcode less

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
Also, I've noticed that currently `CMakeLists.txt` has a bit messy variable names: some of them have DIR_ prefix, others have CMAKE_ prefix, and to override the default values one needs to define variables without any specific prefix. Maybe use [this](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) instead?

**Comment by Jehan** [comment]
I am not a CMake expert and welcomes any proposition which makes sense. I guess using GNU naming is a good idea and indeed makes sense.

**Comment by Jehan** [comment]
Merged. Thanks.
Feel free to propose GNU variable naming in another pull request.

**Comment by Coacher** [comment]
> Feel free to propose GNU variable naming in another pull request.
Will do. Hopefully soon.

**Pull request merged**
