### PR TITLE
cmake: uniform indent everywhere

### PR DESCRIPTION
**Pull request by Coacher**
Indent with tabs, remove leading/trailing blank lines and spaces.

### CODE REVIEW

**Comment by Jehan** [comment]
Sorry, looks like this is now conflicting after merging other commits. Could you fix, and I'll push immediately. :-)
Thanks!

**Comment by Coacher** [comment]
Done. Please also notice commit 8906244.

**Comment by Jehan** [comment]
The contributor of commit f53cb8c proposed an alternative with double quotes instead of single quotes, which seems to be good with every type of builds.
Could you just remove this commit 4c80dd4 and I'll merge the indent fixes. Thanks!

**Comment by Coacher** [comment]
I've updated it again to remove the conflicting commit.

**Comment by Jehan** [comment]
Thanks.

**Pull request merged**
